#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        TankDeviceServer.py
#
#  Project :     TankDeviceServer
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      thomas.madsen$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["TankDeviceServer", "TankDeviceServerClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
import random

#----- PROTECTED REGION ID(TankDeviceServer.additionnal_import) ENABLED START -----#

#----- PROTECTED REGION END -----#	//	TankDeviceServer.additionnal_import

# Device States Description
# No states for this device


class TankDeviceServer (PyTango.Device_4Impl):
    """"""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(TankDeviceServer.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	TankDeviceServer.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        TankDeviceServer.init_device(self)
        #----- PROTECTED REGION ID(TankDeviceServer.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TankDeviceServer.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(TankDeviceServer.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TankDeviceServer.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_Weight_read = 0.0
        self.attr_Pressure_read = 0.0
        self.attr_Flow_read = 0.0
        self.attr_Valve_read = False
        #----- PROTECTED REGION ID(TankDeviceServer.init_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TankDeviceServer.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(TankDeviceServer.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TankDeviceServer.always_executed_hook

    # -------------------------------------------------------------------------
    #    TankDeviceServer read/write attribute methods
    # -------------------------------------------------------------------------
    
    def read_Weight(self, attr):
        self.debug_stream("In read_Weight()")
        #----- PROTECTED REGION ID(TankDeviceServer.Weight_read) ENABLED START -----#
	self.attr_Weight_read = random.uniform(0,100)

        attr.set_value(self.attr_Weight_read)
        
        #----- PROTECTED REGION END -----#	//	TankDeviceServer.Weight_read
        
    def read_Pressure(self, attr):
        self.debug_stream("In read_Pressure()")
        #----- PROTECTED REGION ID(TankDeviceServer.Pressure_read) ENABLED START -----#
	self.attr_Pressure_read = random.uniform(0,10)

        attr.set_value(self.attr_Pressure_read)
        
        #----- PROTECTED REGION END -----#	//	TankDeviceServer.Pressure_read
        
    def read_Flow(self, attr):
        self.debug_stream("In read_Flow()")
        #----- PROTECTED REGION ID(TankDeviceServer.Flow_read) ENABLED START -----#
	self.attr_Flow_read = random.uniform(0,1)

        attr.set_value(self.attr_Flow_read)
        
        #----- PROTECTED REGION END -----#	//	TankDeviceServer.Flow_read
        
    def read_Valve(self, attr):
        self.debug_stream("In read_Valve()")
        #----- PROTECTED REGION ID(TankDeviceServer.Valve_read) ENABLED START -----#
        attr.set_value(self.attr_Valve_read)
        
        #----- PROTECTED REGION END -----#	//	TankDeviceServer.Valve_read
        
    def write_Valve(self, attr):
        self.debug_stream("In write_Valve()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(TankDeviceServer.Valve_write) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TankDeviceServer.Valve_write
        
    
    
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(TankDeviceServer.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TankDeviceServer.read_attr_hardware


    # -------------------------------------------------------------------------
    #    TankDeviceServer command methods
    # -------------------------------------------------------------------------
    

    #----- PROTECTED REGION ID(TankDeviceServer.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	TankDeviceServer.programmer_methods

class TankDeviceServerClass(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(TankDeviceServer.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	TankDeviceServer.global_class_variables


    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        }


    #    Attribute definitions
    attr_list = {
        'Weight':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'Polling period': "1000",
            } ],
        'Pressure':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'Polling period': "1000",
            } ],
        'Flow':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'Polling period': "1000",
            } ],
        'Valve':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'Memorized':"true_without_hard_applied"
            } ],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(TankDeviceServerClass, TankDeviceServer, 'TankDeviceServer')
        #----- PROTECTED REGION ID(TankDeviceServer.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	TankDeviceServer.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
