#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        PreMixDeviceServer.py
#
#  Project :     PreMixDeviceServer
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      thomas.madsen$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["PreMixDeviceServer", "PreMixDeviceServerClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(PreMixDeviceServer.additionnal_import) ENABLED START -----#

#----- PROTECTED REGION END -----#	//	PreMixDeviceServer.additionnal_import

# Device States Description
# No states for this device


class PreMixDeviceServer (PyTango.Device_4Impl):
    """"""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(PreMixDeviceServer.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	PreMixDeviceServer.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        PreMixDeviceServer.init_device(self)
        #----- PROTECTED REGION ID(PreMixDeviceServer.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PreMixDeviceServer.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(PreMixDeviceServer.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PreMixDeviceServer.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_Temperature_read = 0.0
        self.attr_Pressure_read = 0.0
        self.attr_PressureIndicator_read = 0.0
        self.attr_Flow_read = 0.0
        #----- PROTECTED REGION ID(PreMixDeviceServer.init_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PreMixDeviceServer.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(PreMixDeviceServer.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PreMixDeviceServer.always_executed_hook

    # -------------------------------------------------------------------------
    #    PreMixDeviceServer read/write attribute methods
    # -------------------------------------------------------------------------
    
    def read_Temperature(self, attr):
        self.debug_stream("In read_Temperature()")
        #----- PROTECTED REGION ID(PreMixDeviceServer.Temperature_read) ENABLED START -----#
        attr.set_value(self.attr_Temperature_read)
        
        #----- PROTECTED REGION END -----#	//	PreMixDeviceServer.Temperature_read
        
    def read_Pressure(self, attr):
        self.debug_stream("In read_Pressure()")
        #----- PROTECTED REGION ID(PreMixDeviceServer.Pressure_read) ENABLED START -----#
        attr.set_value(self.attr_Pressure_read)
        
        #----- PROTECTED REGION END -----#	//	PreMixDeviceServer.Pressure_read
        
    def read_PressureIndicator(self, attr):
        self.debug_stream("In read_PressureIndicator()")
        #----- PROTECTED REGION ID(PreMixDeviceServer.PressureIndicator_read) ENABLED START -----#
        attr.set_value(self.attr_PressureIndicator_read)
        
        #----- PROTECTED REGION END -----#	//	PreMixDeviceServer.PressureIndicator_read
        
    def read_Flow(self, attr):
        self.debug_stream("In read_Flow()")
        #----- PROTECTED REGION ID(PreMixDeviceServer.Flow_read) ENABLED START -----#
        attr.set_value(self.attr_Flow_read)
        
        #----- PROTECTED REGION END -----#	//	PreMixDeviceServer.Flow_read
        
    
    
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(PreMixDeviceServer.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PreMixDeviceServer.read_attr_hardware


    # -------------------------------------------------------------------------
    #    PreMixDeviceServer command methods
    # -------------------------------------------------------------------------
    

    #----- PROTECTED REGION ID(PreMixDeviceServer.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	PreMixDeviceServer.programmer_methods

class PreMixDeviceServerClass(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(PreMixDeviceServer.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	PreMixDeviceServer.global_class_variables


    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        }


    #    Attribute definitions
    attr_list = {
        'Temperature':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'Polling period': "1000",
            } ],
        'Pressure':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'Polling period': "1000",
            } ],
        'PressureIndicator':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'Polling period': "1000",
            } ],
        'Flow':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ],
            {
                'Polling period': "1000",
            } ],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(PreMixDeviceServerClass, PreMixDeviceServer, 'PreMixDeviceServer')
        #----- PROTECTED REGION ID(PreMixDeviceServer.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PreMixDeviceServer.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
