#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        DistributionDeviceServer.py
#
#  Project :     DistributionDeviceServer
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      thomas.madsen$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["DistributionDeviceServer", "DistributionDeviceServerClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(DistributionDeviceServer.additionnal_import) ENABLED START -----#
import random

#----- PROTECTED REGION END -----#	//	DistributionDeviceServer.additionnal_import

# Device States Description
# No states for this device


class DistributionDeviceServer (PyTango.Device_4Impl):
    """"""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(DistributionDeviceServer.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	DistributionDeviceServer.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        DistributionDeviceServer.init_device(self)
        #----- PROTECTED REGION ID(DistributionDeviceServer.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	DistributionDeviceServer.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(DistributionDeviceServer.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	DistributionDeviceServer.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_Valve101_read = False
        self.attr_Valve201_read = False
        self.attr_Valve301_read = False
        self.attr_Valve400_read = False
        #----- PROTECTED REGION ID(DistributionDeviceServer.init_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	DistributionDeviceServer.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(DistributionDeviceServer.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	DistributionDeviceServer.always_executed_hook

    # -------------------------------------------------------------------------
    #    DistributionDeviceServer read/write attribute methods
    # -------------------------------------------------------------------------
    
    def read_Valve101(self, attr):
        self.debug_stream("In read_Valve101()")
        #----- PROTECTED REGION ID(DistributionDeviceServer.Valve101_read) ENABLED START -----#
        attr.set_value(self.attr_Valve101_read)
        
        #----- PROTECTED REGION END -----#	//	DistributionDeviceServer.Valve101_read
        
    def write_Valve101(self, attr):
        self.debug_stream("In write_Valve101()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(DistributionDeviceServer.Valve101_write) ENABLED START -----#
	self.attr_Valve101_read = data        

        #----- PROTECTED REGION END -----#	//	DistributionDeviceServer.Valve101_write
        
    def read_Valve201(self, attr):
        self.debug_stream("In read_Valve201()")
        #----- PROTECTED REGION ID(DistributionDeviceServer.Valve201_read) ENABLED START -----#
        attr.set_value(self.attr_Valve201_read)
        
        #----- PROTECTED REGION END -----#	//	DistributionDeviceServer.Valve201_read
        
    def write_Valve201(self, attr):
        self.debug_stream("In write_Valve201()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(DistributionDeviceServer.Valve201_write) ENABLED START -----#
	self.attr_Valve201_read = data            

        #----- PROTECTED REGION END -----#	//	DistributionDeviceServer.Valve201_write
        
    def read_Valve301(self, attr):
        self.debug_stream("In read_Valve301()")
        #----- PROTECTED REGION ID(DistributionDeviceServer.Valve301_read) ENABLED START -----#
        attr.set_value(self.attr_Valve301_read)
        
        #----- PROTECTED REGION END -----#	//	DistributionDeviceServer.Valve301_read
        
    def write_Valve301(self, attr):
        self.debug_stream("In write_Valve301()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(DistributionDeviceServer.Valve301_write) ENABLED START -----#
        self.attr_Valve301_read = data    

        #----- PROTECTED REGION END -----#	//	DistributionDeviceServer.Valve301_write
        
    def read_Valve400(self, attr):
        self.debug_stream("In read_Valve400()")
        #----- PROTECTED REGION ID(DistributionDeviceServer.Valve400_read) ENABLED START -----#
        attr.set_value(self.attr_Valve400_read)
        
        #----- PROTECTED REGION END -----#	//	DistributionDeviceServer.Valve400_read
        
    def write_Valve400(self, attr):
        self.debug_stream("In write_Valve400()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(DistributionDeviceServer.Valve400_write) ENABLED START -----#
	self.attr_Valve400_read = data    
        
        #----- PROTECTED REGION END -----#	//	DistributionDeviceServer.Valve400_write
        
    
    
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(DistributionDeviceServer.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	DistributionDeviceServer.read_attr_hardware


    # -------------------------------------------------------------------------
    #    DistributionDeviceServer command methods
    # -------------------------------------------------------------------------
    

    #----- PROTECTED REGION ID(DistributionDeviceServer.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	DistributionDeviceServer.programmer_methods

class DistributionDeviceServerClass(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(DistributionDeviceServer.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	DistributionDeviceServer.global_class_variables


    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        }


    #    Attribute definitions
    attr_list = {
        'Valve101':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'Memorized':"true_without_hard_applied"
            } ],
        'Valve201':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'Memorized':"true_without_hard_applied"
            } ],
        'Valve301':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'Memorized':"true_without_hard_applied"
            } ],
        'Valve400':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'Memorized':"true_without_hard_applied"
            } ],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(DistributionDeviceServerClass, DistributionDeviceServer, 'DistributionDeviceServer')
        #----- PROTECTED REGION ID(DistributionDeviceServer.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	DistributionDeviceServer.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
